// Mocks generated by Mockito 5.3.2 from annotations
// in smiler/test/unit/usecase/get_photo_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:smiler/data/repository/imitation_repository_impl.dart' as _i3;
import 'package:smiler/data/source/model/result.dart' as _i2;
import 'package:smiler/domain/model/scoring_result.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ImitationRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockImitationRepositoryImpl extends _i1.Mock
    implements _i3.ImitationRepositoryImpl {
  @override
  _i4.Future<_i2.Result<String>> getEmotionImage(String? emotionName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmotionImage,
          [emotionName],
        ),
        returnValue: _i4.Future<_i2.Result<String>>.value(_FakeResult_0<String>(
          this,
          Invocation.method(
            #getEmotionImage,
            [emotionName],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<String>>.value(_FakeResult_0<String>(
          this,
          Invocation.method(
            #getEmotionImage,
            [emotionName],
          ),
        )),
      ) as _i4.Future<_i2.Result<String>>);
  @override
  _i4.Future<_i2.Result<_i5.ScoringResult>> isCorrectImitation(
    String? answerEmotionName,
    String? imagePath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isCorrectImitation,
          [
            answerEmotionName,
            imagePath,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.ScoringResult>>.value(
            _FakeResult_0<_i5.ScoringResult>(
          this,
          Invocation.method(
            #isCorrectImitation,
            [
              answerEmotionName,
              imagePath,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Result<_i5.ScoringResult>>.value(
                _FakeResult_0<_i5.ScoringResult>(
          this,
          Invocation.method(
            #isCorrectImitation,
            [
              answerEmotionName,
              imagePath,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.ScoringResult>>);
}
